import { fetchFinancialAnalysis } from "@/lib/data/google";
import { Financials } from "@/lib/types/edinet-db";
import Markdown from "react-markdown";
import remarkGfm from "remark-gfm";

export default async function GeminiFinancialAnalysis({ balanceSheets }: { balanceSheets: Financials[] }) {
    const financialAnalysisResponse = await fetchFinancialAnalysis(balanceSheets)
    if ("error" in financialAnalysisResponse) {
        console.error("Error fetching financial analysis:", financialAnalysisResponse.error)
        return <div>Error: {financialAnalysisResponse.error}</div>
    }
    const { data: analysis } = financialAnalysisResponse
  
  return (
    <div className="mt-8">
      <h2 className="text-2xl font-bold mb-4">Financial Analysis by AI</h2>
      <p className="mb-4 text-sm text-muted-foreground">
        This analysis is generated by AI and provided for informational purposes only. It is not a guarantee of performance and should not be taken as professional advice. The website, creator, and operator accept no responsibility or liability for its accuracy or any decisions made based on it.
      </p>
      <Markdown remarkPlugins={[remarkGfm]}>{analysis}</Markdown>
    </div>
  )
}